FROM python:3.10-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    ffmpeg \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN pip install -e third_party/VectorizedMultiAgentSimulator

RUN pip install -e third_party/BenchMARL

RUN pip install -e .

CMD ["/bin/bash"]
