# CUDA 12.3 + cuDNN + Ubuntu 22.04
FROM nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04

# =====================
# ????????????
# =====================
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace


RUN apt-get update && apt-get install -y \
    python3.10 \
    python3.10-dev \
    python3-pip \
    git \
    build-essential \
    ffmpeg \
    xvfb \
    libgl1 \
    libglib2.0-0 \
    libglu1-mesa \
    python3-opengl \
    && rm -rf /var/lib/apt/lists/*


# ?????? python ?????? python3.10
RUN ln -sf /usr/bin/python3.10 /usr/bin/python


# =====================
# Python??????
# =====================
RUN python -m pip install --upgrade pip setuptools wheel


# =====================
# PyTorch CUDA??????
# =====================
RUN pip install \
    torch==2.6.0 \
    torchvision==0.21.0 \
    torchaudio==2.6.0 \
    --index-url https://download.pytorch.org/whl/cu124

# =====================
# ????????????
# =====================
COPY docker/requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN pip install -e third_party/VectorizedMultiAgentSimulator

RUN pip install -e third_party/BenchMARL

CMD ["/bin/bash"]
